repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: flake8
      args: ['--exclude=docs/*,*migrations*', '--ignore=E501']
