language: python

python:
  - "3.6"

install:
    - pip install pipenv
    - pipenv install --dev
    - pipenv install coveralls

before_script:
    - pipenv run flake8 --ignore=E501 simple_model

script:
    - pipenv run py.test
    - pipenv run mypy simple_model

after_script:
    - pipenv run coveralls
